branch-defaults:
  default:
    environment: Getting-started-env
environment-defaults:
  Getting-started-env:
    branch: null
    repository: null
global:
  application_name: getting-started
  default_ec2_keyname: null
  default_platform: Node.js 22 running on 64bit Amazon Linux 2023
  default_region: ap-south-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: null
  workspace_type: Application
